### ISSUE TITLE
Generated code does not map optional fields to Kotlin nullable variables

### ISSUE THREAD

**Issue by julienfouilhe** [connectrpc/connect-kotlin#255]
Hi,

One of the most annoying issues with GRPC in Kotlin is that the generated kotlin code does not work with `optional`.

It generates the following code:

```
    /**
     * `optional uint32 min_transaction_amount_in_cents = 5 [json_name = "minTransactionAmountInCents"];`
     */
    public var minTransactionAmountInCents: kotlin.Int
      @JvmName("getMinTransactionAmountInCents")
      get() = _builder.getMinTransactionAmountInCents()
      @JvmName("setMinTransactionAmountInCents")
      set(value) {
        _builder.setMinTransactionAmountInCents(value)
      }
    /**
     * `optional uint32 min_transaction_amount_in_cents = 5 [json_name = "minTransactionAmountInCents"];`
     */
    public fun clearMinTransactionAmountInCents() {
      _builder.clearMinTransactionAmountInCents()
    }
    /**
     * `optional uint32 min_transaction_amount_in_cents = 5 [json_name = "minTransactionAmountInCents"];`
     * @return Whether the minTransactionAmountInCents field is set.
     */
    public fun hasMinTransactionAmountInCents(): kotlin.Boolean {
      return _builder.hasMinTransactionAmountInCents()
    }
```

Which means that you need to think about using the `has` method to know if your field is present or not, because they set the default value. It's not the case with swift, rust or javascript
When I saw that `connect-kotlin` was out, I was hopeful that you would have fixed this problem, but I saw that connectrpc/kotlin depended on protocolbuffers/kotlin and figured you would still have this issue. Confirmed after trying it.

Do you plan on fixing it or is it a behaviour you're okay with? Do you know if there's a solution (besides rewriting the files)?

**Comment by srikrsna-buf** [comment]
I believe this a protobuf runtime API design problem and beyond the scope of connect. There's a closed issue on this topic: https://github.com/protocolbuffers/protobuf/issues/10178

**Comment by jhump** [comment]
> Do you plan on fixing it or is it a behaviour you're okay with?

As @srikrsna-buf points out, this is not something we can fix because it is not in connect-kotlin. This is a property of the underlying protobuf runtime, which we don't own/maintain.

> It's not the case with swift, rust or javascript

Nor Go. But this _is_ the behavior with C++, Python, and Java. The Kotlin implementation is built on top of the protobuf-java generated code and runtime.

FWIW, it is actually possible to use connect-kotlin with alternate protobuf runtimes. This capability is what currently allows you to pick the lite runtime vs. the standard runtime. But it could also be used to select a completely different runtime and generated code, such as [square/wire](https://github.com/square/wire/). You would need to implement a custom [`SerializationStrategy`](https://github.com/connectrpc/connect-kotlin/blob/v0.6.1/library/src/main/kotlin/com/connectrpc/SerializationStrategy.kt) that uses the alternate runtime to serialize and de-serialize messages to/from bytes. Connect-kotlin does not include an extension for square/wire, but at an early point in the project, we did try it out. So it should be possible to implement this in user code.

**Comment by ln-12** [comment]
@julienfouilhe when I am generating the code, there is a `fieldOrNull` property generated along the members you mentioned which internally checks the `hasField` method. So I am just using that instead of the plain `field`.
