### ISSUE TITLE
Consider interacting with the network off the calling thread

### ISSUE THREAD

**Issue by jzbrooks** [connectrpc/connect-kotlin#313]
When retrofit added suspend support, its suspending functions ran the actual network interaction off the calling thread. While it's fairly easy to wrap connect-kotlin generated suspend calls in a `withContext` dispatch, having that thread switch happen automatically seems less error prone. Since we use both buf and retrofit in our codebase, this is a relatively common source of confusion that often results in `NetworkOnMainThreadException`s.

Square's implementation uses their own executor, but using the built-in `Dispatchers.IO` might work too? I'm unsure which would be preferable.

https://github.com/square/retrofit/pull/2886

**Comment by jhump** [comment]
@jzbrooks, what version are you using? As of v0.5.0, you can set a property on the `ProtocolClientConfig` so that this dispatch happens automatically. The change was made here: #218.

**Comment by jzbrooks** [comment]
Hey @jhump, that's exactly what I was looking for. I missed that note on the release. Thanks!

**Comment by erawhctim** [comment]
Any reason why this isn't enabled by default?

**Comment by jhump** [comment]
> Any reason why this isn't enabled by default?

@erawhctim, at the time I added it, I was concerned about it being surprising behavior. Also it's not backwards compatible: if you have application code that did not configure this new property and explicitly dispatched to a particular context, the library under the hood would re-dispatch back to its default context, which may be surprising or problematic.

I'm certainly open to changing the default behavior though before we get to a v1.0.0 release. But I was thinking of making that change in the same release as other more significant (and backwards-incompatible) API changes, so that it's less likely to be overlooked when someone upgrades.

**Comment by erawhctim** [comment]
very wise; that makes a lot of sense 👍 Setting that as the default for v1.0 sounds ideal.
